---
- hosts: all
  become: true

  tasks:

    - name: copy wallpaper file
      copy:
        src: files/wallpaper.jpg
        dest: /home/ann/Pictures/ansible-wallpaper.jpg
        owner: ann
        group: ann

    - name: set wallpaper
      become: true
      become_user: ann
      environment:
        DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
      xfconf:
        channel: "xfce4-desktop"
        property: "/backdrop/screen0/monitorVirtual1/workspace0/last-image"
        value_type: string
        value: "/home/ann/Pictures/ansible-wallpaper.jpg"



# xfconf-query -c xfce4-desktop -p /uuckdrop/screen0/monitoVirtual1/workspace0/last-image -s /home/ann/Pictures/ansible-wallpaper.jpg
#
# - c --channel the channel to query/modify
# - p --property the property to query/modify
# - s --set the new value to set for the property
